### ISSUE TITLE
Crash on loading

### ISSUE THREAD

**Issue by CatExperimenters** [JayJay1989/gamesense-sdk#1]
When I try to load the game with this mod I get this error:
'The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from GameSense Mod (gamesense)'
Putting the json file in the mods folder didn't help and if it matters then I'm also using other mods. I'm also using 1.10.2 and can't update to a newer version.

**Comment by JayJay1989** [comment]
Which version of the mod and Forge?

**Comment by JayJay1989** [comment]
When i'm home, i recompile the mod with the json library included, so no need for the json-xxxx.jar file.

**Comment by JayJay1989** [comment]
@CatExperimenters please try this one: [Link](https://github.com/JayJay1989/gamesense-sdk/releases/download/1.12.2/gamesense-1.12-forge1.12.2.jar)

Remove the json-xxxx.jar file in your mods folder!!

**Comment by CatExperimenters** [comment]
I get an error 404 :/

**Comment by CatExperimenters** [comment]
That fixed it. Thanks a lot
