### ISSUE TITLE
(gamesense-1.12-forge1.12.2.jar) Don't recognize Minecraft when you switch servers too fast.

### ISSUE THREAD

**Issue by SkyMinecraft01** [JayJay1989/gamesense-sdk#2]
I wanted to play a game on a Minecraft server, but when you choose a game, you automatically switch to another server (the game server). But the problem is that the mod has detected that I was leaving the server, but it does not detect that I am going to another...

The mod would have to detect that I'm on Minecraft even if it changes server too fast, otherwise, I can't play games on servers with my mouse :'(

Thank you

(Translated from French to English with  www.DeepL.com/Translator)

**Comment by JayJay1989** [comment]
Its something in the bungeecord code. I cant fix it. The only advice i can give, dont use bungeecord, use [Waterfall](https://ci.destroystokyo.com/job/Waterfall/)

**Comment by SkyMinecraft01** [comment]
Good morning,
Maybe, but I'm talking more about other people's servers, or popular servers (for example Hypixel).

You really can't do anything to make it detect the game? Or make it happen a little bit all the time to always check if we're in play, or something like that?

Because it's very annoying not to be able to use your mouse with Minecraft :( Especially since I almost bought it just for that...

Thank you

**Comment by JayJay1989** [comment]
I actually tested in forge environment, and even when i go to the "nether" or "the end" i have the same issue. Trying to fix it

**Comment by JayJay1989** [comment]
unzip this zip and place the jar in your mod folder. Let me know if its fixed
[gamesense-1.12.1.jar.zip](https://github.com/JayJay1989/gamesense-sdk/files/1821828/gamesense-1.12.1.jar.zip)

**Comment by SkyMinecraft01** [comment]
Good evening,

Indeed, it works, I just tested 2 minutes and for the moment, it works well. But I noticed that, sometimes, some hits are not detected and the mouse does not vibrate. I noticed it when I got shot.

Thank you

**Comment by JayJay1989** [comment]
tactile doesnt work on damage. 
![screenshot](https://user-images.githubusercontent.com/1212803/37845092-f1df7388-2ec9-11e8-943b-5aef89437053.png)

**Comment by SkyMinecraft01** [comment]
I know... I already put this on.

**Comment by JayJay1989** [comment]
@SkyMinecraft01 can you try something for me (its mc 1.8.9, unzip the file in attachment) ? i added an eventhandler for taking damage/hurt. It will be send as HURT with data 1 if you get damage/hurt. 0 when nothing happened. Post your lsp also ;)

[gamesense-1.12-forge.1.8.9.jar.zip](https://github.com/JayJay1989/gamesense-sdk/files/2222801/gamesense-1.12-forge.1.8.9.jar.zip)
