### ISSUE TITLE
1.8.9 Won't launch

### ISSUE THREAD

**Issue by AzureAqua** [JayJay1989/gamesense-sdk#3]
[crash-2018-07-24_01.52.46-client.txt](https://github.com/JayJay1989/gamesense-sdk/files/2221556/crash-2018-07-24_01.52.46-client.txt)
When I try to launch it, it crashes :(

**Comment by JayJay1989** [comment]
i look into it

**Comment by JayJay1989** [comment]
uploaded a wrong mod for 1.8.9. Check here for the latest build.

**Comment by AzureAqua** [comment]
Now it says "There was an error connecting to Steelseries engine 3". I was playing on a server, if that helps

**Comment by JayJay1989** [comment]
is steelseries installed?

**Comment by AzureAqua** [comment]
![image](https://user-images.githubusercontent.com/41600194/43136577-1afd4b64-8f41-11e8-9f4f-4c76d121311d.png)

**Comment by JayJay1989** [comment]
weird, i tried it and have no problems or whatever.
![screenshot_13](https://user-images.githubusercontent.com/1212803/43154205-d23889d8-8f73-11e8-8b78-500bb9d13500.png)

**Comment by AzureAqua** [comment]
:/ I have some other mods installed (Optifine and 5zig), maybe that's affecting it?

**Comment by JayJay1989** [comment]
installed optifine and 5zig mod. Working just fine here :/ maybe try reinstalling steelseries software could help?

**Comment by AzureAqua** [comment]
Okay, I'll try that

**Comment by AzureAqua** [comment]
Wait, um it's suddenly working.
