### ISSUE TITLE
The only way I can send you a message, sorry =/

### ISSUE THREAD

**Issue by Kirillism** [JayJay1989/gamesense-sdk#6]
I saw you forked the Gamesense-sdk, SteelSeries aren't helpful at all. Have you come across a method or a way to retrieve values from the local web engine itself? 

What I wanted to to is retrieve the current color of PrismSync and relay the color to my own custom built LED strip.

**Comment by JayJay1989** [comment]
so far i know its not possible.  Maybe you can tamper the usb to see whats been send to the steelseries devices.

**Comment by Kirillism** [comment]
Thank you for the fast response! I'll close the ticket and try to listen on my local address via Wireshark =/ !

**Comment by JayJay1989** [comment]
helpfull article: [steelseries Arduino](https://techblog.steelseries.com/2016/04/06/gamesense-arduino.html)
